services:
  - type: web
    name: tshedza-portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt --no-cache-dir
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application --log-level debug --access-logfile - --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: PIP_NO_CACHE_DIR
        value: "true"
      - key: ALLOWED_HOSTS
        value: "tshedza-portofilio.onrender.com,localhost,127.0.0.1" 